### ISSUE TITLE
Jenkins builds often fail on PR checks when tests actually run fine

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#278]
**Describe the bug**
What often happens when submitting a PR to this repo is:

1. Two Jenkins builds are automatically triggered - `continuous-integration/jenkins/pr-merge` and `continuous-integration/jenkins/branch`
2. Often, one or both of these builds will fail, saying there are test failures.
3. However, there are actually no test failures - tests run fine, and if these Jenkins builds were retried, they would succeed.

What will get reported by Jenkins (via the build step - Jest output) is something similar to this:

```
[2021-08-11T14:03:16.033Z] Summary of all failing tests

[2021-08-11T14:03:16.033Z] FAIL src/app/wizards/dataElement/data-element-step2/data-element-step2.component.spec.ts

[2021-08-11T14:03:16.033Z]   ● Test suite failed to run

[2021-08-11T14:03:16.033Z] 

[2021-08-11T14:03:16.033Z]     jest: failed to cache transform results in: /tmp/jest_35/jest-transform-cache-2a3af16c3d4f8b9dd1532568fe174208-d1d5bfaad8659acd06069518d3e76e6c/8e/dataelementstep2componentspec_8ec898fd4608330d682592d33498d3a7.map

[2021-08-11T14:03:16.033Z]     Failure message: ENOENT: no such file or directory, open '/tmp/jest_35/jest-transform-cache-2a3af16c3d4f8b9dd1532568fe174208-d1d5bfaad8659acd06069518d3e76e6c/8e/dataelementstep2componentspec_8ec898fd4608330d682592d33498d3a7.map.2567472006'

[2021-08-11T14:03:16.033Z] 

[2021-08-11T14:03:16.033Z]       at writeFileSync (node_modules/write-file-atomic/index.js:205:13)

[2021-08-11T14:03:16.033Z]       at writeCacheFile (node_modules/@jest/transform/build/ScriptTransformer.js:792:33)

[2021-08-11T14:03:16.033Z]       at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:537:7)

[2021-08-11T14:03:16.033Z]       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)

[2021-08-11T14:03:16.033Z]       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)

[2021-08-11T14:03:16.033Z] 

[2021-08-11T14:03:16.033Z] FAIL src/app/shared/path-name/path-name.service.spec.ts

[2021-08-11T14:03:16.033Z]   ● Test suite failed to run

[2021-08-11T14:03:16.033Z] 

[2021-08-11T14:03:16.033Z]     jest: failed to cache transform results in: /tmp/jest_35/jest-transform-cache-2a3af16c3d4f8b9dd1532568fe174208-d1d5bfaad8659acd06069518d3e76e6c/89/pathnameservicespec_89ae9f56fec219001ea5c9b1ab902047.map

[2021-08-11T14:03:16.033Z]     Failure message: ENOENT: no such file or directory, open '/tmp/jest_35/jest-transform-cache-2a3af16c3d4f8b9dd1532568fe174208-d1d5bfaad8659acd06069518d3e76e6c/89/pathnameservicespec_89ae9f56fec219001ea5c9b1ab902047.map.1515355957'

[2021-08-11T14:03:16.033Z] 

[2021-08-11T14:03:16.033Z]       at writeFileSync (node_modules/write-file-atomic/index.js:205:13)

[2021-08-11T14:03:16.033Z]       at writeCacheFile (node_modules/@jest/transform/build/ScriptTransformer.js:792:33)

[2021-08-11T14:03:16.033Z]       at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:537:7)

[2021-08-11T14:03:16.033Z]       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)

[2021-08-11T14:03:16.033Z]       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

These errors have nothing to do with the tests themselves, there just seems to be an error writing to test result logs.

**Comment by olliefreeman** [comment]
@pjmonks is it possible to override the temp directory for jest at runtime using arguments ????

**Comment by olliefreeman** [comment]
Ignore that….it’s the “cacheDirectory” which we can provide at runtime, I’ll figure out the best way to make it dynamic
