### ISSUE TITLE
Cannot save a data model with the dynamic standard profile

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-ui#321]
1. Create a dynamic data standard profile with one text field (non mandatory field)
2. Create a data model, and try to add the profile from that standard profile. 
3. Enter values for the profile. Attempt to validate. Attempt the Save.

Behavior:
3. When user clicks on the Validate button no feedback sent to the end user
4. When user clicks on Save, Nullpointer exception is thrown in the UI.

Expected behavior: 
User can validate the data model, and save afterwards with no issues. The field was not mandatory, and a free text.

MDM_APPLICATION_COMMIT: 4.10.0
MDM_UI_COMMIT: 6.6.0

**Comment by jelenadreskai** [comment]
Log:
2021-09-22 00:17:48,394 [080-exec-5] ERROR o.g.web.errors.GrailsExceptionResolver : NullPointerException occurred when processing request: [POST] /api/dataModels/a2835e45-a5f0-4902-ac94-7f22c2bd1f3b/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/DataStandardTest100

Stacktrace follows:


java.lang.NullPointerException: null

at uk.ac.ox.softeng.maurodatamapper.profile.provider.EmptyJsonProfileFactory.loadNewProfileStructure(EmptyJsonProfileFactory.groovy:61)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at uk.ac.ox.softeng.maurodatamapper.profile.provider.EmptyJsonProfileFactory.getOrLoadProfileStructure(EmptyJsonProfileFactory.groovy:54)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at uk.ac.ox.softeng.maurodatamapper.profile.provider.EmptyJsonProfileFactory.getEmptyProfile(EmptyJsonProfileFactory.groovy:37)

at uk.ac.ox.softeng.maurodatamapper.profile.provider.JsonProfileProviderService.getNewProfile(JsonProfileProviderService.groovy:59)

at uk.ac.ox.softeng.maurodatamapper.profile.ProfileController.$tt__save(ProfileController.groovy:146)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)

at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)

at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)

at java.base/java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_L(VirtualHandle.java:130)

at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)

at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)

at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)

at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)

at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)

at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)

**Comment by GBishop-PHSA** [comment]
The uk.ac.ox.softeng.maurodatamapper.profile.provider.DynamicJsonProfileProviderService#getJsonResourceFile method returns null, but the call to uk.ac.ox.softeng.maurodatamapper.profile.provider.EmptyJsonProfileFactory#loadNewProfileStructure, expects a non-null value. 

Would returning an empty string from loadNewProfileStructure when the jsonResourceFile is null be the right fix or should the DynamicJsonProfileProviderService have a json file associated with it?
